name = "sveltekit-supabase"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "build",entry-point = "workers-site"}
compatibility_date = "2021-11-08"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
